[package]
name        = "flix-pretty"
description = "A pretty print library for Flix."
version     = "0.10.1"
flix        = "0.69.3"
license     = "Apache-2.0"
authors     = ["Stephen Tetley <stephen.tetley@gmail.com>"]

